/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestorApp.vista;

import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import modelo.Pedido;

/**
 *
 * @author SG0208533
 */
public class PanelPedidosTomados extends javax.swing.JPanel {

    private ActionListener aListener;
        
    public PanelPedidosTomados(ActionListener al, ArrayList<Pedido> pedidos) {
        initComponents();
        this.aListener = al;
        mostrar(pedidos);
        
    }
    
    public void mostrar(ArrayList<Pedido> pedidos){
        pnlListaPedidos.removeAll();
        pnlListaPedidos.setLayout(new GridLayout(0,1));
        if(pedidos != null){
            for(Pedido p : pedidos){
                BotonPedido b = new BotonPedido(p);
                b.addActionListener(aListener);
                pnlListaPedidos.add(b);
            }
        }
        pnlListaPedidos.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlListaPedidos = new javax.swing.JPanel();
        lblPedidos = new javax.swing.JLabel();

        setLayout(null);

        pnlListaPedidos.setLayout(new java.awt.GridLayout(1, 0));
        add(pnlListaPedidos);
        pnlListaPedidos.setBounds(20, 60, 360, 510);

        lblPedidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPedidos.setText("Lista de Pedidos Tomados");
        add(lblPedidos);
        lblPedidos.setBounds(0, 20, 400, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPedidos;
    private javax.swing.JPanel pnlListaPedidos;
    // End of variables declaration//GEN-END:variables
}
